LINKEDIN_CLIENT_ID = "SEU_CLIENT_ID_AQUI"
LINKEDIN_CLIENT_SECRET = "SEU_CLIENT_SECRET_AQUI"
REDIRECT_URI = "http://localhost:8501" # Para testes locais
LINKEDIN_ORG_ID = "ID COMPANY DA P√ÅGINA"
LINKEDIN_PAGE_ACCESS_TOKEN = "TOKEN"